### ISSUE TITLE
Pi connect 

### ISSUE THREAD

**Issue by ZatmanOptionz24** [pi-apps/2345pi-app-nav#1]
Check out this Pi Brainstorm project idea. Follow this link to read more details about it pi://brainstorm.pi/project/6394d2a309b2820c1eb0fb7e

**Comment by bailaoshijiadao** [comment]
> Check out this Pi Brainstorm project idea. Follow this link to read more details about it pi://brainstorm.pi/project/6394d2a309b2820c1eb0fb7e

I am unable to open this page
